export enum MessageRole {
  USER = 'user',
  MODEL = 'model',
  ERROR = 'error',
}

export interface ChatMessage {
  role: MessageRole;
  content: string;
}

export enum AlertSeverity {
  INFO = 'Info',
  MEDIUM = 'Medium',
  HIGH = 'High',
  CRITICAL = 'Critical',
}

export interface Device {
    type: 'Desktop' | 'Server' | 'Mobile' | 'Laptop' | 'IoT Device' | 'Firewall' | 'Cloud VM' | 'Container';
    os: 'Windows' | 'Linux' | 'Android' | 'macOS' | 'Embedded Linux' | 'PAN-OS' | 'Ubuntu';
    hostname: string;
    ip_address: string;
    last_seen: string;
    agent_version: string;
    firewall_status: 'Enabled' | 'Disabled';
    disk_encryption: 'Enabled' | 'Disabled';
    status: 'Online' | 'Offline' | 'Alerting';
}

export interface AlertContext {
    industry: 'Financial' | 'Healthcare' | 'Government' | 'Retail' | 'Manufacturing';
    country: string;
    continent: string;
    region: string;
}

export interface Alert {
  id: string;
  severity: AlertSeverity;
  title: string;
  description: string;
  timestamp: string;
  raw_data?: Record<string, any> & { device: Device; context: AlertContext }; 
}

export type LearningSource = 'MITRE ATT&CK' | 'VirusTotal' | 'AlienVault OTX' | 'CVE Database' | 'Splunk SIEM' | 'Microsoft Defender' | 'NVD/EPSS' | 'OSV' | 'Exploit-DB' | 'Antivirus Detections';

// Event forwarded by the Lightweight Server or generated by the Server Brain
export interface ServerEvent {
  id:string;
  type: 'AGGREGATED_EVENT' | 'LEARNING_UPDATE' | 'DIRECTIVE_PUSH' | 'KNOWLEDGE_SYNC' | 'PROACTIVE_ALERT_PUSH' | 'AUTOMATED_REMEDIATION';
  timestamp: string;
  payload: AggregatedEvent | LearningUpdate | DirectivePush | KnowledgeSync | ProactiveAlertPush | AutomatedRemediation;
}

// Represents one or more agent alerts, aggregated and sanitized
export interface AggregatedEvent {
  title: string;
  severity: AlertSeverity;
  count: number;
  sanitized_data: Record<string, any>;
  first_seen: string;
  last_seen: string;
  context?: AlertContext;
}

// Represents the central server learning from external sources
export interface LearningUpdate {
  source: LearningSource;
  summary: string;
  details?: VulnerabilityDetails;
}

export interface VulnerabilityDetails {
    cve_id: string;
    cvss_score: number;
    affected_software: string;
    advisory_link: string;
}

// Represents the server pushing new intelligence to agents
export interface DirectivePush {
    title: string;
    description: string;
    target: 'All Agents' | 'Specific OS';
}

// Represents the server syncing its knowledge to the LWServer/Agents
export interface KnowledgeSync {
    description: string;
    version: string;
}

// Represents a targeted, proactive warning to a specific group of agents
export interface ProactiveAlertPush {
    title: string;
    threat_summary: string;
    target_context: string; // e.g., "Financial Sector in Europe"
}

// Represents a single event that contributes to the server's knowledge
export interface KnowledgeContribution {
    id: string;
    timestamp: string;
    source: string; // e.g., "Critical Alert: Ransomware" or "Intel: VirusTotal"
    points: number;
    newTotal: number;
}

// Represents an automated response to a critical threat
export interface AutomatedRemediation {
    threat_name: string;
    actions_taken: ('Isolate Host' | 'Terminate Process Tree' | 'Delete File')[];
    target_host: string;
}


export type AllEventTypes = Alert | ServerEvent;